[package]
name = "bot_go_brr"
version = "4.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.safe-vex]
version = "2.2.2"
# path = "../../safe-vex"
features = [ "simulate" ]

[profile.release]
incremental = false
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
incremental = true
debug = false

[profile.dev.package."*"]
opt-level = 3
