[package]
name = "bot_go_brr"
version = "4.7.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
safe-vex = { path = "../../safe-vex", features = [ "simulate" ] }

[profile.release]
incremental = true

[profile.dev]
incremental = true
debug = false

[profile.dev.package."*"]
opt-level = 3