[package]
name = "bot_go_brr"
version = "3.4.5-stripped-1.0.0"
authors = ["GreenChild04 <greenchild04@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.vex-rt]
# Comment out the version line and uncomment the git line to use pre-release versions.
version = "0.15.1"
# git = "https://gitlab.com/qvex/vex-rt.git"

[profile.release]
incremental = true

[profile.dev]
incremental = true
debug = false

[profile.dev.package."*"]
opt-level = 3