[package]
name = "bot_go_brr"
version = "5.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.safe-vex]
# version = "3.1.3"
path = "../../safe-vex"

[features]

[profile.release]
incremental = false
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[profile.dev]
incremental = true
debug = false

[profile.dev.package."*"]
opt-level = 3
