[book]
authors = ["GreenChild04"]
language = "en"
multilingual = false
src = "src"
title = "Vex VRC Robotics Team 97230F's Digital Engineering Notebook"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
